language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source

script: phpunit

notifications:
  email:
    - andreas.glaser@protonmail.com

cache:
  directories:
    - $HOME/.composer/cache